### ISSUE TITLE
when export default in tsx file, it will transform any variables to $HotComponent

### ISSUE THREAD

**Issue by fanioc** [solidjs/solid-refresh#3]
![image](https://user-images.githubusercontent.com/33722465/141937700-051ca25a-9f61-4a49-aae4-8c828d710005.png)

![image](https://user-images.githubusercontent.com/33722465/141937887-8c3085aa-e43a-4bf8-a347-187d63aff59e.png)

When I use `export default ` in a `tsx` file,  it will transform any variables to $HotComponent, it seems to be a bug.

**Comment by ryansolid** [comment]
I guess we could add some smarter heuristics but this plugin is designed to assume that the default export of a .jsx/.tsx file is a component that needs to be wrapped. There is no perfect heuristic to determine if something is a component. I'm not saying this won't ever be improved, but it can be tricky.  Maybe its better to err on the side of not wrapping. Like if we can't determine its a function don't wrap? In any case might take a little doing to come up with the right balance here.

**Comment by ryansolid** [comment]
Fixed in the latest.
