### ISSUE TITLE
Esbuild support?

### ISSUE THREAD

**Issue by woodcox** [solidjs/solid-refresh#32]
Is there esbuild support for solid-refresh? I use the [esbuild-plugin-solid](https://github.com/amoutonbrady/esbuild-plugin-solid) rather than vite.

**Comment by woodcox** [comment]
Would it work with a similar approach to [esbuild-hmr](https://github.com/jacob-ebey/esbuild-hmr)?

**Comment by lxsmnsyc** [comment]
well for that kind of setup you'd need to write an esbuild plugin that uses transform + solid-refresh w/ esm setup

**Comment by woodcox** [comment]
Yeah building an esbuild-solid-hmr plugin is probably a bit beyond my JS skill level at the moment. But maybe longer term it’s something I could figure out……

**Comment by lxsmnsyc** [comment]
Since ESBuild doesn't have an HMR API this issue is a `wontfix`
