### ISSUE TITLE
no mechanism for universal renderers

### ISSUE THREAD

**Issue by Alloyed** [solidjs/solid-refresh#44]
It looks like the babel plugin hardcodes the identities of certain solid-js variables to detect them later:

https://github.com/solidjs/solid-refresh/blob/22d6a92c91013b6e5d71e520a3d1dcb47d491bba/src/babel/index.ts#L234C1-L239C3

This is all well and good, but because I'm using a universal renderer, my render function isn't actually at `solid-js/web`! could the plugin provide a means of customizing this, specifically?

**Comment by lxsmnsyc** [comment]
Yeah I forgot about that. I'll work on this soon.

**Comment by ryansolid** [comment]
This should be fixed in the next version.
