### ISSUE TITLE
Inaccurate information in readme - parcel support can be added

### ISSUE THREAD

**Issue by danieltroger** [solidjs/solid-refresh#49]
In the readme it states

> ParcelJS doesn't support [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) yet, which makes ParcelJS load the production build of SolidJS instead of its development build. Solid Refresh requires the SolidJS development build to work.

However, parcel supports package.json#exports since 6+ months back (however behind a flag until they release 3.0.0), see https://github.com/parcel-bundler/parcel/issues/4155 and https://parceljs.org/blog/v2-9-0/#new-resolver

**Comment by lxsmnsyc** [comment]
I'm not doubting that, but my claim was pretty accurate the last time I made the commit: https://github.com/solidjs/solid-refresh/commit/21c4df5ad2c55520f5c592dfa70585564bfb6907

Of course at the time of its release there wasn't any config support for it. Funnily enough, I recall some issues in Parcel besides it. Will probably have to test this again for actual confirmation.

**Comment by danieltroger** [comment]
Yeah, would be cool with parcel HMR support. Right now we just have full page reloads all the time in our parcel projects.
