### ISSUE TITLE
Should async `onCleanup` be expected to have been completed before HMR respawns a component?

### ISSUE THREAD

**Issue by Enteleform** [solidjs/solid-refresh#69]
I ran into an issue with a third-party library that has a registration/unregistration process which is causing errors during HMR due to an unexpected order of events.

To prevent this error, the following event order would be required:
- [Component-1] created
- [Component-1] cleanup.start
- [Component-1] cleanup.end
- [Component-2] created

But this is what's actually occurring:
- [Component-1] created
- [Component-1] cleanup.start
- [Component-2] created
- [Component-1] cleanup.end

Here's a minimal repro:
https://stackblitz.com/edit/solid-vite-lynwpq?file=src%2Findex.tsx

**Comment by lxsmnsyc** [comment]
it's expected. HMR is usually fast enough to reload before that 1s timeout can even run.

**Comment by Enteleform** [comment]
Would it be possible to add an option for `solid-refresh` that waits for `onCleanup` to finish before respawning components?

And are there any recommended workarounds/patterns for avoiding this issue?

**Comment by lxsmnsyc** [comment]
No, because even Solid doesn't manage async lifecycle callbacks. You'll have to manage this on your own.

**Comment by Enteleform** [comment]
Gotcha, thanks for the info 👍
