### ISSUE TITLE
useContext doesn't get value in dev mode

### ISSUE THREAD

**Issue by geohuz** [solidjs/solid-refresh#71]
### Describe the bug

the useContext get null value in dev mode. According to the documentation: 

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-c5vdbu?file=src%2FContext.jsx

Basically I have a error handler to check for the default value of the context in hooks.jsx, like this:

```jsx
export function useCounter() {
  const value = useContext(CounterContext);
  if (!value) {
    throw new Error(
      "useCounter must be used within a CounterContext.Provider ",
    );
  }
  return value;
}
```

### Steps to Reproduce the Bug or Issue

Change the source code, (eg. comment) in the context.jsx then the error:

```
Uncaught (in promise) Error: useCounter must be used within a CounterContext.Provider 
    at useCounter (hooks.jsx:7:11)
....
```

appears in the console. Have to refresh the page to remove the error.

### Expected behavior

The error shouldn't appear in dev mode.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by atilafassina** [comment]
> This is an known HMR constraint. One that seems to lead to getting reported every other month. I'm going to move it there.
> 
> The gist of it is the createContext call should be in a different file than where the provider is used. The way context HMR works in Solid causes it to get mismatched if they are in the same file. Since for some reason the issue keeps getting closed I'm going to move this to solid-refresh. I'm also going to flag the docs team as this seems to get reported a lot.

Hopefully I adjusted all snippets correctly and entered more explanation to prevent this

https://github.com/solidjs/solid-docs/pull/956

**Comment by geohuz** [comment]
Thanks all!

**Comment by lxsmnsyc** [comment]
@Huliiiiii  that's because the HMR transform only covers the JSX/TSX files, so that transformed is applied correctly, whereas it is untouched in JS/TS files.
