### ISSUE TITLE
Unhandled `render` calls

### ISSUE THREAD

**Issue by LXSMNSYC** [solidjs/solid-refresh#8]
https://github.com/solidjs/solid/issues/768

This issue has been solved regardless, however most of the people who uses HMR won't realize this issue. We have `// @refresh reload` as a workaround however this requires manual input and most of the time people aren't aware of this solution (maybe due to lack of understanding for HMR). We might want to handle this automatically.

I have a solution in mind, scan the `Program` for  `ExpressionStatement`s with `CallExpression` and `render` being called. We then inject an HMR `dispose` call to perform the cleanup `render` returns. Another one would be to inject the same script `// @refresh reload` emits with the same check.

I'm also thinking of handling `createRoot` calls.

**Comment by adharshmk96** [comment]
I'm still facing the issue. I had to fix it using 
```const dispose = render(() => <App />, root!);
if (import.meta.hot) {
  import.meta.hot.dispose(dispose);
}```

**Comment by adharshmk96** [comment]
```// @refresh reload
import './index.css';
import { render } from 'solid-js/web';

import App from './App';

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  );
}

render(() => <App />, root!);
```  also not working.

i just used `npx degit solidjs/templates/ts-tailwindcss my-app`
